// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt9xqQ62d8R2JF8wsAJo07jitrezaDU3A',
    appId: '1:150287340690:web:481d42d4ab398c1f83024b',
    messagingSenderId: '150287340690',
    projectId: 'easyparty-10860',
    authDomain: 'easyparty-10860.firebaseapp.com',
    storageBucket: 'easyparty-10860.appspot.com',
    measurementId: 'G-NLC0PFVE6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbxGhn7KCj03pvCXGSoxbRAdP3DLb3FyY',
    appId: '1:150287340690:android:006876d51551742383024b',
    messagingSenderId: '150287340690',
    projectId: 'easyparty-10860',
    storageBucket: 'easyparty-10860.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM-2Ptuw877LD2HxjTNcyRk11JK83r0Qo',
    appId: '1:150287340690:ios:962af9f6251fddf683024b',
    messagingSenderId: '150287340690',
    projectId: 'easyparty-10860',
    storageBucket: 'easyparty-10860.appspot.com',
    iosBundleId: 'com.example.easyParty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM-2Ptuw877LD2HxjTNcyRk11JK83r0Qo',
    appId: '1:150287340690:ios:35ade6a5a0feeaa283024b',
    messagingSenderId: '150287340690',
    projectId: 'easyparty-10860',
    storageBucket: 'easyparty-10860.appspot.com',
    iosBundleId: 'com.example.easyParty.RunnerTests',
  );
}
